"""
Healthcare profession and specialty taxonomy.

Derived from: Professions, Specialities - 2.11.26 updates.xlsx
Sheets: "Nursing - Specialties" + "Allied Health - Specialties"

Provides:
  SPECIALTY_ABBREVIATIONS  — abbrev/shorthand → canonical full name
  SPECIALTY_GROUPS         — canonical specialty → group label
  PROFESSION_ABBREVIATIONS — credential abbrev → full profession name
  NURSING_SPECIALTIES      — all valid nursing specialty names (canonical)
  ALLIED_HEALTH_SPECIALTIES — all valid allied health specialty names
  ALL_SPECIALTIES          — combined deduplicated list
"""

import re

# ── Profession credential expansions ─────────────────────────────────────────
# Used to normalize credential strings found on resumes
PROFESSION_ABBREVIATIONS: dict[str, str] = {
    "rn": "Registered Nurse",
    "lpn": "Licensed Practical Nurse",
    "lvn": "Licensed Vocational Nurse",
    "lpn/lvn": "Licensed Practical Nurse / Licensed Vocational Nurse",
    "cna": "Certified Nursing Assistant",
    "crna": "Certified Registered Nurse Anesthetist",
    "np": "Nurse Practitioner",
    "fnp": "Family Nurse Practitioner",
    "apn": "Advanced Practice Nurse",
    "aprn": "Advanced Practice Registered Nurse",
    "rnfa": "Registered Nurse First Assistant",
    "crt": "Certified Respiratory Therapist",
    "rrt": "Registered Respiratory Therapist",
    "ot": "Occupational Therapist",
    "cota": "Certified Occupational Therapy Assistant",
    "pt": "Physical Therapist",
    "pta": "Physical Therapist Assistant",
    "slp": "Speech-Language Pathologist",
    "slpa": "Speech-Language Pathologist Assistant",
    "csw": "Certified Social Worker",
    "lcsw": "Licensed Clinical Social Worker",
    "licsw": "Licensed Independent Clinical Social Worker",
    "lmsw": "Licensed Master Social Worker",
    "msw": "Masters of Social Work",
    "lmft": "Licensed Marriage and Family Therapist",
    "lpcc": "Licensed Professional Clinical Counselor",
    "lpc": "Licensed Professional Counselor",
    "emt": "Emergency Medical Technician",
    "ma": "Medical Assistant",
    "picc": "Peripherally Inserted Central Catheter Nurse",
    "mds": "Minimum Data Set Coordinator",
}

# ── Specialty abbreviations → canonical full name ─────────────────────────────
# Only entries where the Excel SpecialtyFull column was non-empty,
# plus common shorthand variants seen on real resumes.
SPECIALTY_ABBREVIATIONS: dict[str, str] = {
    # ── Nursing ───────────────────────────────────────────────────────────────
    "bicu": "Burn Intensive Care Unit",
    "burn icu": "Burn Intensive Care Unit",
    "bmt": "Bone Marrow Transplant",
    "bone marrow transplant": "Bone Marrow Transplant",
    "cticu": "Cardiothoracic Intensive Care Unit",
    "ct icu": "Cardiothoracic Intensive Care Unit",
    "ccu": "Critical Care Unit",
    "chemo": "Chemotherapy",
    "covid icu": "Intensive Care Unit",
    "cvcc": "Cardiovascular Critical Care",
    "cvicu": "Cardiovascular Intensive Care Unit",
    "cardiovascular icu": "Cardiovascular Intensive Care Unit",
    "cvor": "Cardiovascular Operating Room",
    "cvpicu": "Cardiovascular Pediatric Intensive Care Unit",
    "dou": "Definitive Observation Unit",
    "echo lab": "Echocardiography Laboratory",
    "ep lab": "Electrophysiology Laboratory",
    "electrophysiology lab": "Electrophysiology Laboratory",
    "er": "Emergency Room",
    "ed": "Emergency Department",
    "emergency department": "Emergency Room",
    "er holding": "Emergency Room Holding",
    "gi lab": "Gastrointestinal Laboratory",
    "gi/endo": "Gastrointestinal / Endoscopy",
    "icu": "Intensive Care Unit",
    "icu float": "Intensive Care Unit Float",
    "imcu": "Intermediate Care Unit",
    "ltac": "Long-Term Acute Care",
    "ltac icu": "Long-Term Acute Care Intensive Care Unit",
    "ltac telemetry": "Long-Term Acute Care Telemetry",
    "ltac tele": "Long-Term Acute Care Telemetry",
    "ltc": "Long-Term Care",
    "mds coordinator": "Minimum Data Set Coordinator",
    "micu": "Medical Intensive Care Unit",
    "medical icu": "Medical Intensive Care Unit",
    "med surg": "Medical Surgical",
    "ms": "Medical Surgical",
    "med/surg": "Medical Surgical",
    "neuro icu": "Neurological Intensive Care Unit",
    "nicu": "Neonatal Intensive Care Unit",
    "nicu transport": "Neonatal Intensive Care Unit Transport",
    "ob/gyn": "Obstetrics and Gynecology",
    "ob gyn": "Obstetrics and Gynecology",
    "obgyn": "Obstetrics and Gynecology",
    "or": "Operating Room",
    "pacu": "Post-Anesthesia Care Unit",
    "post anesthesia care unit": "Post-Anesthesia Care Unit",
    "pcu": "Progressive Care Unit",
    "pcu float": "Progressive Care Unit Float",
    "pcu oncology": "Progressive Care – Oncology",
    "pcu - oncology": "Progressive Care – Oncology",
    "pediatric bmt": "Pediatric Bone Marrow Transplant",
    "pediatric cvor": "Pediatric Cardiovascular Operating Room",
    "pediatric er": "Pediatric Emergency Room",
    "pediatric ltac": "Pediatric Long-Term Acute Care",
    "pediatric micu": "Pediatric Medical Intensive Care Unit",
    "pediatric or": "Pediatric Operating Room",
    "pediatric pacu": "Pediatric Post-Anesthesia Care Unit",
    "pediatric pcu": "Pediatric Progressive Care Unit",
    "picc nurse": "Peripherally Inserted Central Catheter Nurse",
    "picu": "Pediatric Intensive Care Unit",
    "preop": "Pre-Operative",
    "pre-op": "Pre-Operative",
    "pre op": "Pre-Operative",
    "rnfa": "Registered Nurse First Assistant",
    "rn first assistant": "Registered Nurse First Assistant",
    "sicu": "Surgical Intensive Care Unit",
    "surgical icu": "Surgical Intensive Care Unit",
    "snf": "Skilled Nursing Facility",
    "tcu": "Transitional Care Unit",
    "transitional care": "Transitional Care Unit",
    "tele": "Telemetry",
    "tele float": "Telemetry Float",
    "trauma icu": "Trauma Intensive Care Unit",
    # ── Allied Health — Radiology & Cardiology ────────────────────────────────
    "ct tech": "CT Technologist (Computed Tomography)",
    "computed tomography tech": "CT Technologist (Computed Tomography)",
    "computed tomography": "CT Technologist (Computed Tomography)",
    "ekg tech": "EKG Technician (Electrocardiography)",
    "ecg tech": "EKG Technician (Electrocardiography)",
    "electrocardiography": "EKG Technician (Electrocardiography)",
    "eeg tech": "EEG Technician (Electroencephalography)",
    "electroencephalography technician": "EEG Technician (Electroencephalography)",
    "mri tech": "MRI Technologist (Magnetic Resonance Imaging)",
    "magnetic resonance imaging tech": "MRI Technologist (Magnetic Resonance Imaging)",
    "magnetic resonance imaging": "MRI Technologist (Magnetic Resonance Imaging)",
    "ir tech": "Interventional Radiology Tech",
    "x-ray tech": "X-Ray Technologist",
    "xray tech": "X-Ray Technologist",
    "cath lab tech": "Cardiac Catheterization Lab Technologist",
    "echo tech": "Echocardiography Technologist",
    "echo tech - cardiac sonographer": "Echocardiography Technologist",
    "echo tech - cardiac sonographer peds": "Echocardiography Technologist – Pediatric",
    "cardiac sonographer": "Echocardiography Technologist",
    "ultrasound tech - general ii": "Ultrasound Tech – General II",
    "eeg tech manager": "EEG Technician Manager",
    "electroencephalography technician manager": "EEG Technician Manager",
    "cvor tech": "Cardiovascular Operating Room Tech",
    # ── Allied Health — Respiratory & Neuro ───────────────────────────────────
    "crt": "Certified Respiratory Therapist",
    "rrt": "Registered Respiratory Therapist",
    "rrt float": "Registered Respiratory Therapist",
    "rrt pediatrics": "Registered Respiratory Therapist – Pediatrics",
    "rrt picu": "Registered Respiratory Therapist – PICU",
    "rrt nicu": "Registered Respiratory Therapist – NICU",
    "crt nicu": "Certified Respiratory Therapist – NICU",
    # ── Allied Health — Therapy & Rehab ───────────────────────────────────────
    "ot": "Occupational Therapist",
    "cota": "Certified Occupational Therapy Assistant",
    "pt": "Physical Therapist",
    "pt aide": "Physical Therapy Aide",
    "pta": "Physical Therapist Assistant",
    "slp": "Speech-Language Pathologist",
    "slpa": "Speech-Language Pathologist Assistant",
    # ── Allied Health — Surgical Services ────────────────────────────────────
    "or tech": "Operating Room Technologist / Surgical Tech",
    "surgical tech": "Operating Room Technologist / Surgical Tech",
    "or tech / surgical tech": "Operating Room Technologist / Surgical Tech",
    "certified or tech / surgical tech (cst)": "Certified Surgical Technologist",
    "cvor certified surgical first assistant": "Cardiovascular Operating Room Surgical First Assistant",
    "pediatric cvor tech": "Pediatric Cardiovascular Operating Room Tech",
    "pediatric or tech / surgical tech": "Pediatric Operating Room Tech / Surgical Tech",
    "spt": "Sterile Processing Technician",
    "sterile processing tech": "Sterile Processing Technician",
    "sterile processing tech (spt)": "Sterile Processing Technician",
    "pediatric sterile processing tech (spt)": "Pediatric Sterile Processing Technician",
    "sterile processing tech (spt) director": "Sterile Processing Director",
    "sterile processing tech (spt) manager": "Sterile Processing Manager",
    "sterile processing tech (spt) team lead": "Sterile Processing Team Lead",
    "gi/endo tech": "Gastrointestinal / Endoscopy Technician",
    "ob tech": "Obstetric Technician",
    "cst": "Certified Surgical Technologist",
    # ── Allied Health — Social Services ──────────────────────────────────────
    "csw": "Certified Social Worker",
    "csw (certified social worker)": "Certified Social Worker",
    "lcsw": "Licensed Clinical Social Worker",
    "lcsw (licensed clinical social worker)": "Licensed Clinical Social Worker",
    "licsw": "Licensed Independent Clinical Social Worker",
    "licsw (licensed independent clinical social worker)": "Licensed Independent Clinical Social Worker",
    "lmsw": "Licensed Master Social Worker",
    "lmsw (licensed master social worker)": "Licensed Master Social Worker",
    "msw": "Masters of Social Work",
    "msw (masters of social work)": "Masters of Social Work",
    # ── Allied Health — Laboratory ────────────────────────────────────────────
    "cls": "Clinical Lab Scientist",
    "mlt": "Medical Lab Technician",
    "mt": "Medical Technologist",
    "mls": "Medical Lab Scientist",
    # ── Allied Health — Medical Assistant ────────────────────────────────────
    "ma - allergy and immunology": "Medical Assistant – Allergy and Immunology",
    "ma - dermatology": "Medical Assistant – Dermatology",
    "ma - family practice": "Medical Assistant – Family Practice",
    "ma - internal medicine": "Medical Assistant – Internal Medicine",
    "ma - ob/gyn": "Medical Assistant – OB/GYN",
    "ma - oncology": "Medical Assistant – Oncology",
    "ma - pediatrics": "Medical Assistant – Pediatrics",
    "ma - urgent care": "Medical Assistant – Urgent Care",
    "ma - snf/ltc": "Medical Assistant – SNF/LTC",
    "ma - medical assistant": "Medical Assistant",
}

# ── Specialty → Group mapping ─────────────────────────────────────────────────
# Maps canonical specialty name → group label (broad category)
SPECIALTY_GROUPS: dict[str, str] = {
    # Nursing groups
    "Acute Care Float": "Med Surg",
    "Administrative": "Manager",
    "Ambulatory Care": "Primary Care",
    "Antepartum": "Labor and Delivery",
    "Apheresis": "Dialysis",
    "Bariatrics": "Med Surg",
    "Behavioral Health": "Behavioral Health",
    "Burn Intensive Care Unit": "ICU",
    "Bone Marrow Transplant": "Oncology",
    "Cardiac Tele": "Med Surg / Tele",
    "Cardiothoracic Intensive Care Unit": "ICU",
    "Case Manager": "Case Manager",
    "Cath Lab": "Cath Lab",
    "Cath Lab Holding": "Cath Lab",
    "Critical Care Unit": "ICU",
    "Chemotherapy": "Oncology",
    "Clinical Decisions": "Stepdown",
    "Clinical Documentation Specialist": "Educator",
    "Clinical Education Specialist": "Educator",
    "Clinical Research Coordinator": "Clinical Research Nurse",
    "Clinical Research Nurse (CRN)": "Clinical Research Nurse",
    "Correctional": "Behavioral Health",
    "Intensive Care Unit": "ICU",
    "Intensive Care Unit Float": "ICU",
    "COVID Testing": "Vaccination Support",
    "Critical Care Float": "ICU",
    "Critical Care Transport": "Critical Care Transport",
    "Cardiovascular Critical Care": "ICU",
    "Cardiovascular Intensive Care Unit": "ICU",
    "Cardiovascular Operating Room": "Operating Room",
    "Cardiovascular Pediatric Intensive Care Unit": "Pediatrics",
    "Dialysis": "Dialysis",
    "Director": "Manager",
    "Discharge Planner": "Case Manager",
    "Definitive Observation Unit": "Stepdown",
    "Echocardiography Laboratory": "Echo Lab",
    "Educator": "Educator",
    "Emergency Transport Traveler": "Critical Care Transport",
    "Endoscopy": "Endoscopy",
    "Electrophysiology Laboratory": "Cath Lab",
    "Emergency Room": "ER",
    "Emergency Room Holding": "Med Surg / Tele",
    "Flight Nurse": "Critical Care Transport",
    "Geriatric Behavioral Health": "Behavioral Health",
    "Geriatrics": "LTC",
    "Gastrointestinal Laboratory": "Endoscopy",
    "Hematology/Oncology": "Oncology",
    "Home Health": "Home Health",
    "Hospice": "Home Health",
    "House Supervisor": "Manager",
    "Hyperbaric": "Wound Care",
    "Intermediate Care Unit": "Stepdown",
    "Interventional Radiology": "Cath Lab",
    "Invasive Procedure": "Cath Lab",
    "Labor and Delivery": "Labor and Delivery",
    "Long-Term Acute Care": "LTAC",
    "Long-Term Acute Care Intensive Care Unit": "LTAC",
    "Long-Term Acute Care Telemetry": "LTAC",
    "Long-Term Care": "LTC",
    "Manager": "Manager",
    "Maternal Fetal Care": "Nursery",
    "Medical Surgical": "Med Surg",
    "Medical Intensive Care Unit": "ICU",
    "Mother Baby": "Nursery",
    "Med Surg / Tele": "Med Surg / Tele",
    "Neurological Intensive Care Unit": "ICU",
    "New Graduate": "New Graduate",
    "Neonatal Intensive Care Unit": "Nursery",
    "Neonatal Intensive Care Unit Transport": "Nursery",
    "Nurse Instructor": "Educator",
    "Nursery": "Nursery",
    "Obstetrics and Gynecology": "Outpatient Clinic",
    "Observation Unit": "Med Surg / Tele",
    "Occupational Health": "Outpatient Clinic",
    "Oncology": "Oncology",
    "Open Heart": "Operating Room",
    "Operating Room": "Operating Room",
    "Ortho": "Med Surg",
    "Outpatient Clinic": "Outpatient Clinic",
    "Post-Anesthesia Care Unit": "PACU",
    "Progressive Care Unit": "Stepdown",
    "Pre-Operative": "PACU",
    "Pediatric Intensive Care Unit": "Pediatrics",
    "Peripherally Inserted Central Catheter Nurse": "Pediatrics",
    "Primary Care": "Primary Care",
    "Quality Coordinator": "Case Manager",
    "Quality Management": "Case Manager",
    "Radiation Oncology": "Oncology",
    "Rehab": "LTC",
    "Registered Nurse First Assistant": "Operating Room",
    "School Nurse": "School RN",
    "Surgical Intensive Care Unit": "ICU",
    "Skilled Nursing Facility": "LTC",
    "Stepdown": "Stepdown",
    "Stepdown Cardiac": "Stepdown",
    "Stepdown Neuro": "Stepdown",
    "Sub-Acute": "LTAC",
    "Transitional Care Unit": "Stepdown",
    "Telemetry": "Med Surg / Tele",
    "Trauma Intensive Care Unit": "ICU",
    "Urgent Care": "Outpatient Clinic",
    "Utilization Review": "Case Manager",
    "Vaccination Support": "Vaccination Support",
    "Wound Care": "Wound Care",
    # Allied Health groups
    "Behavioral Health Assistant": "Behavioral Health",
    "Behavioral Health Tech": "Behavioral Health",
    "Mental Health Tech": "Behavioral Health",
    "Clinical Lab Scientist": "Laboratory",
    "Cyto Tech": "Laboratory",
    "Laboratory Director": "Laboratory",
    "Embryologist": "Laboratory",
    "Histology Tech": "Laboratory",
    "Laboratory Assistant": "Laboratory",
    "Laboratory Manager": "Laboratory",
    "Medical Lab Scientist": "Laboratory",
    "Medical Lab Technician": "Laboratory",
    "Medical Technologist": "Laboratory",
    "Phlebotomist": "Laboratory",
    "CT Technologist (Computed Tomography)": "Imaging Tech",
    "EKG Technician (Electrocardiography)": "Imaging Tech",
    "Interventional Radiology Tech": "Imaging Tech",
    "Mammography Tech": "Imaging Tech",
    "MRI Technologist (Magnetic Resonance Imaging)": "Imaging Tech",
    "Sonographer": "Imaging Tech",
    "Ultrasound Tech – General": "Imaging Tech",
    "X-Ray Technologist": "Imaging Tech",
    "Certified Respiratory Therapist": "Respiratory",
    "Registered Respiratory Therapist": "Respiratory",
    "EEG Technician (Electroencephalography)": "Neuro",
    "Certified Social Worker": "Social Worker",
    "Licensed Clinical Social Worker": "Social Worker",
    "Licensed Independent Clinical Social Worker": "Social Worker",
    "Licensed Master Social Worker": "Social Worker",
    "Masters of Social Work": "Social Worker",
    "Medical Social Worker": "Social Worker",
    "School Social Worker": "Social Worker",
    "Occupational Therapist": "OT",
    "Certified Occupational Therapy Assistant": "COTA",
    "Physical Therapist": "PT",
    "Physical Therapist Assistant": "PTA",
    "Speech-Language Pathologist": "SLP",
    "Speech-Language Pathologist Assistant": "SLPA",
    "Operating Room Technologist / Surgical Tech": "OR Tech",
    "Sterile Processing Technician": "Sterile Processing",
    "Cardiovascular Operating Room Tech": "OR Tech",
    "Obstetric Technician": "OR Tech",
    # ── Completed from the 2.11.26 spreadsheet (Speciality → Group) ───────────
    "Cardiac Catheterization Lab Technologist": "Imaging Tech",
    "Cardiac Stress Testing": "Echo Lab",
    "Cardiovascular Operating Room Surgical First Assistant": "OR Tech",
    "Case Worker": "Social Worker",
    "Certified OB Tech": "OR Tech",
    "Certified Occupational Therapist Assistant – School": "COTA",
    "Certified Occupational Therapy Assistant – Acute Care": "COTA",
    "Certified Occupational Therapy Assistant – Behavioral Health": "COTA",
    "Certified Occupational Therapy Assistant – Home Health": "COTA",
    "Certified Occupational Therapy Assistant – Inpatient Rehab": "COTA",
    "Certified Occupational Therapy Assistant – LTAC": "COTA",
    "Certified Occupational Therapy Assistant – Outpatient": "COTA",
    "Certified Occupational Therapy Assistant – Pediatrics": "COTA",
    "Certified Occupational Therapy Assistant – SNF": "COTA",
    "Certified Occupational Therapy Assistant – School": "COTA",
    "Certified School Nurse": "School RN",
    "Certified Surgical Technologist": "OR Tech",
    "Dietary Aide": "Dietary",
    "Dietary Tech": "Dietary",
    "Dietician": "Dietary",
    "Infusion": "Oncology",
    "Licensed Marriage and Family Therapist": "Social Worker",
    "Licensed Professional Clinical Counselor": "Social Worker",
    "Licensed Professional Counselor": "Social Worker",
    "Med Surg - Neuro": "Med Surg",
    "Med Surg - Oncology": "Med Surg",
    "Med Surg / Tele Float": "Med Surg / Tele",
    "Med Surg Float": "Med Surg",
    "Medical Assistant": "Medical Assistant",
    "Medical Assistant – Acute Float Pool": "Medical Assistant",
    "Medical Assistant – Allergy and Immunology": "Medical Assistant",
    "Medical Assistant – Dermatology": "Medical Assistant",
    "Medical Assistant – Family Practice": "Medical Assistant",
    "Medical Assistant – Internal Medicine": "Medical Assistant",
    "Medical Assistant – OB/GYN": "Medical Assistant",
    "Medical Assistant – Oncology": "Medical Assistant",
    "Medical Assistant – Otorhinolaryngology (ENT)": "Medical Assistant",
    "Medical Assistant – Pain Management": "Medical Assistant",
    "Medical Assistant – Pediatrics": "Medical Assistant",
    "Medical Assistant – SNF/LTC": "Medical Assistant",
    "Medical Assistant – Urgent Care": "Medical Assistant",
    "Medical Assistant – Vaccination Support": "Medical Assistant",
    "Mental Health": "Social Worker",
    "Metabolomic Technician": "Laboratory",
    "Microbiology Tech": "Laboratory",
    "OR Tech First Assistant": "OR Tech",
    "Occupational Therapist – Acute Care": "OT",
    "Occupational Therapist – Behavioral Health": "OT",
    "Occupational Therapist – Home Health": "OT",
    "Occupational Therapist – Inpatient Rehab": "OT",
    "Occupational Therapist – LTAC": "OT",
    "Occupational Therapist – Outpatient": "OT",
    "Occupational Therapist – Pediatrics": "OT",
    "Occupational Therapist – SNF": "OT",
    "Occupational Therapist – School": "OT",
    "Oncology - Chemo Certified": "Oncology",
    "Oncology - Clinic": "Oncology",
    "Oncology - Pediatric": "Oncology",
    "Outpatient Clinic Cardiology": "Outpatient Clinic",
    "Outpatient Clinic Hematology Oncology": "Oncology",
    "Outpatient Clinic Infusion": "Oncology",
    "Outpatient Clinic Phlebotomy": "Outpatient Clinic",
    "Outpatient Pediatrics": "Pediatrics",
    "Outpatient Surgery": "Operating Room",
    "Pathology Assistant": "Laboratory",
    "Pediatric Acute Care Float Pool": "Pediatrics",
    "Pediatric Ambulatory Care": "Pediatrics",
    "Pediatric Apheresis": "Pediatrics",
    "Pediatric Behavioral Health": "Behavioral Health",
    "Pediatric Bone Marrow Transplant": "Pediatrics",
    "Pediatric Cardiology": "Pediatrics",
    "Pediatric Cardiovascular Operating Room": "Pediatrics",
    "Pediatric Cardiovascular Operating Room Tech": "OR Tech",
    "Pediatric Cath Lab": "Pediatrics",
    "Pediatric Critical Care Float Pool": "Pediatrics",
    "Pediatric Dialysis": "Pediatrics",
    "Pediatric Emergency Room": "Pediatrics",
    "Pediatric Endoscopy": "Pediatrics",
    "Pediatric Home Health": "Pediatrics",
    "Pediatric IV Therapy": "Pediatrics",
    "Pediatric Infusion": "Pediatrics",
    "Pediatric Long-Term Acute Care": "Pediatrics",
    "Pediatric Med Surg": "Pediatrics",
    "Pediatric Medical Intensive Care Unit": "Pediatrics",
    "Pediatric Neuro": "Pediatrics",
    "Pediatric Operating Room": "Pediatrics",
    "Pediatric Operating Room Tech / Surgical Tech": "OR Tech",
    "Pediatric Ortho": "Pediatrics",
    "Pediatric Post-Anesthesia Care Unit": "Pediatrics",
    "Pediatric Progressive Care Unit": "Pediatrics",
    "Pediatric Pulmonary": "Pediatrics",
    "Pediatric Rehab": "Pediatrics",
    "Pediatric Stepdown": "Pediatrics",
    "Pediatric Sterile Processing Technician": "Sterile Processing",
    "Pediatric Telemetry": "Pediatrics",
    "Pediatric Transplant": "Pediatrics",
    "Pediatric Transport": "Pediatrics",
    "Pediatric Wound Care": "Pediatrics",
    "Pediatrics": "Pediatrics",
    "Physical Therapist Assistant – Acute Care": "PTA",
    "Physical Therapist Assistant – Behavioral Health": "PTA",
    "Physical Therapist Assistant – Home Health": "PTA",
    "Physical Therapist Assistant – Inpatient Rehab": "PTA",
    "Physical Therapist Assistant – LTAC": "PTA",
    "Physical Therapist Assistant – Outpatient": "PTA",
    "Physical Therapist Assistant – Pediatrics": "PTA",
    "Physical Therapist Assistant – SNF": "PTA",
    "Physical Therapist Assistant – School": "PTA",
    "Physical Therapist – Acute Care": "PT",
    "Physical Therapist – Behavioral Health": "PT",
    "Physical Therapist – Home Health": "PT",
    "Physical Therapist – Inpatient Rehab": "PT",
    "Physical Therapist – LTAC": "PT",
    "Physical Therapist – Outpatient": "PT",
    "Physical Therapist – Pediatrics": "PT",
    "Physical Therapist – SNF": "PT",
    "Physical Therapist – School": "PT",
    "Physical Therapy Aide": "PTA",
    "Progressive Care Unit Float": "Stepdown",
    "Progressive Care – Oncology": "Stepdown",
    "Radiology Manager": "Manager",
    "Registered Respiratory Therapist – NICU": "Respiratory",
    "Registered Respiratory Therapist – PICU": "Respiratory",
    "Registered Respiratory Therapist – Pediatrics": "Respiratory",
    "School Nurse - 1:1": "School RN",
    "School Nurse - Bus Run": "School RN",
    "School Psychologist": "Social Worker",
    "Social Worker Assistant": "Social Worker",
    "Special Procedures": "Imaging Tech",
    "Speech-Language Pathologist Assistant – Acute Care": "SLPA",
    "Speech-Language Pathologist Assistant – Behavioral Health": "SLPA",
    "Speech-Language Pathologist Assistant – Inpatient Rehab": "SLPA",
    "Speech-Language Pathologist Assistant – LTAC": "SLPA",
    "Speech-Language Pathologist Assistant – Outpatient": "SLPA",
    "Speech-Language Pathologist Assistant – SNF": "SLPA",
    "Speech-Language Pathologist Assistant – School": "SLPA",
    "Speech-Language Pathologist – Acute Care": "SLP",
    "Speech-Language Pathologist – Behavioral Health": "SLP",
    "Speech-Language Pathologist – Home Health": "SLP",
    "Speech-Language Pathologist – Inpatient Rehab": "SLP",
    "Speech-Language Pathologist – LTAC": "SLP",
    "Speech-Language Pathologist – Outpatient": "SLP",
    "Speech-Language Pathologist – Pediatrics": "SLP",
    "Speech-Language Pathologist – SNF": "SLP",
    "Speech-Language Pathologist – School": "SLP",
    "Sterile Processing Director": "Sterile Processing",
    "Sterile Processing Manager": "Sterile Processing",
    "Sterile Processing Team Lead": "Sterile Processing",
    "Student Nurse": "New Graduate",
    "Summer Camp": "School RN",
    "Telemetry Float": "Med Surg / Tele",
    "Ultrasound Tech – General II": "Imaging Tech",
    "Ultrasound Tech – Maternal Fetal": "Imaging Tech",
    "Ultrasound Tech – Vascular": "Imaging Tech",
}

# ── Canonical specialty lists ─────────────────────────────────────────────────

NURSING_SPECIALTIES: list[str] = [
    "Acute Care Float", "Administrative", "Ambulatory Care", "Anesthetist",
    "Antepartum", "Apheresis", "Bariatrics", "Behavioral Health",
    "Burn Intensive Care Unit", "Bone Marrow Transplant", "Cardiac Rehab",
    "Cardiac Stress Testing", "Cardiac Tele", "Cardiothoracic Intensive Care Unit",
    "Case Manager", "Cath Lab", "Cath Lab Holding", "Critical Care Unit",
    "Certified School Nurse", "Chemotherapy", "Clinical Decisions",
    "Clinical Documentation Specialist", "Clinical Education Specialist",
    "Clinical Research Coordinator", "Clinical Research Nurse (CRN)",
    "Correctional", "Intensive Care Unit", "COVID Testing", "Critical Care Float",
    "Critical Care Transport", "Cardiovascular Critical Care",
    "Cardiovascular Intensive Care Unit", "Cardiovascular Operating Room",
    "Cardiovascular Pediatric Intensive Care Unit", "Dialysis", "Director",
    "Discharge Planner", "Definitive Observation Unit", "Echocardiography Laboratory",
    "Educator", "Emergency Transport Traveler", "Endocrinology", "Endoscopy",
    "Electrophysiology Laboratory", "Emergency Room", "Emergency Room Holding",
    "Flight Nurse", "Geriatric Behavioral Health", "Geriatrics",
    "Gastrointestinal Laboratory", "Hematology/Oncology", "Home Health", "Hospice",
    "House Supervisor", "Hyperbaric", "Intensive Care Unit Float",
    "Intermediate Care Unit", "Infection Prevention", "Infusion",
    "Interventional Radiology", "Invasive Procedure", "IV Therapy",
    "Labor and Delivery", "Long-Term Acute Care", "Long-Term Acute Care Intensive Care Unit",
    "Long-Term Acute Care Telemetry", "Long-Term Care", "Manager",
    "Maternal Fetal Care", "Minimum Data Set Coordinator", "Medical Surgical",
    "Med Surg - Neuro", "Med Surg Float", "Med Surg - Oncology",
    "Medical Intensive Care Unit", "Mother Baby", "Med Surg / Tele",
    "Med Surg / Tele Float", "Nephrology", "Neurological Intensive Care Unit",
    "New Graduate", "Neonatal Intensive Care Unit", "Neonatal Intensive Care Unit Transport",
    "Nurse Instructor", "Nurse Navigator", "Nursery", "Obstetrics and Gynecology",
    "Observation Unit", "Occupational Health", "Oncology", "Oncology - Pediatric",
    "Oncology - Chemo Certified", "Oncology - Clinic", "Open Heart", "Operating Room",
    "Ortho", "Outpatient Clinic", "Outpatient Clinic Cardiology",
    "Outpatient Clinic Hematology Oncology", "Outpatient Clinic Infusion",
    "Outpatient Clinic Phlebotomy", "Outpatient Pediatrics", "Outpatient Surgery",
    "Post-Anesthesia Care Unit", "Pain Management", "Progressive Care Unit",
    "Progressive Care Unit Float", "Progressive Care – Oncology",
    "Pediatric Acute Care Float Pool", "Pediatric Ambulatory Care",
    "Pediatric Apheresis", "Pediatric Behavioral Health",
    "Pediatric Bone Marrow Transplant", "Pediatric Cardiology", "Pediatric Cath Lab",
    "Pediatric Critical Care Float Pool", "Pediatric Cardiovascular Operating Room",
    "Pediatric Dialysis", "Pediatric Endoscopy", "Pediatric Emergency Room",
    "Pediatric Home Health", "Pediatric Infusion", "Pediatric IV Therapy",
    "Pediatric Long-Term Acute Care", "Pediatric Med Surg",
    "Pediatric Medical Intensive Care Unit", "Pediatric Neuro",
    "Pediatric Operating Room", "Pediatric Ortho",
    "Pediatric Post-Anesthesia Care Unit", "Pediatric Progressive Care Unit",
    "Pediatric Pulmonary", "Pediatric Rehab", "Pediatric Stepdown",
    "Pediatric Telemetry", "Pediatric Transplant", "Pediatric Transport",
    "Pediatric Wound Care", "Pediatrics",
    "Peripherally Inserted Central Catheter Nurse", "Pediatric Intensive Care Unit",
    "Pre-Operative", "Primary Care", "Public Community Health", "Quality Coordinator",
    "Quality Management", "Radiation Oncology", "Radiology",
    "Radiology Manager", "Referral Coordinator", "Rehab", "Rheumatology",
    "Registered Nurse First Assistant", "School Nurse", "School Nurse - 1:1",
    "School Nurse - Bus Run", "Surgical Intensive Care Unit", "Skilled Nursing Facility",
    "Stepdown", "Stepdown Cardiac", "Stepdown Neuro", "Student Nurse", "Sub-Acute",
    "Summer Camp", "Surveyor", "Transitional Care Unit", "Telemetry Float", "Telemetry",
    "Theragnostics", "Triage / Call Center", "Transplant", "Trauma Intensive Care Unit",
    "Urgent Care", "Utilization Review", "Vaccination Support", "Wound Care",
]

ALLIED_HEALTH_PROFESSIONS: list[str] = [
    "Behavioral Health", "Dialysis", "Dietary Services", "EMT", "Laboratory",
    "Medical Assistant", "Paramedic", "Patient Care Technician", "Perfusionist",
    "Radiology & Cardiology", "Respiratory & Neuro", "Social Services",
    "Surgical Services", "Therapy & Rehab",
]

ALLIED_HEALTH_SPECIALTIES: list[str] = [
    # Behavioral Health
    "Behavioral Health Assistant", "Behavioral Health Tech", "Mental Health Tech",
    # Dialysis
    "Dialysis Tech",
    # Dietary
    "Dietician", "Dietary Aide", "Dietary Tech",
    # EMT
    "Emergency Medical Technician", "EMS Educator",
    # Laboratory
    "Clinical Lab Scientist", "Cyto Tech", "Laboratory Director", "Embryologist",
    "Histology Tech", "Laboratory Assistant", "Laboratory Manager",
    "Medical Lab Scientist", "Medical Lab Technician", "Medical Technologist",
    "Metabolomic Technician", "Microbiology Tech", "Pathology Assistant",
    "Phlebotomist",
    # Medical Assistant
    "Medical Assistant – Allergy and Immunology", "Medical Assistant – Dermatology",
    "Medical Assistant – Family Practice", "Medical Assistant – Acute Float Pool",
    "Medical Assistant – Internal Medicine", "Medical Assistant",
    "Medical Assistant – OB/GYN", "Medical Assistant – Oncology",
    "Medical Assistant – Otorhinolaryngology (ENT)", "Medical Assistant – Pain Management",
    "Medical Assistant – Pediatrics", "Medical Assistant – SNF/LTC",
    "Medical Assistant – Urgent Care", "Medical Assistant – Vaccination Support",
    # Other
    "Paramedic", "Patient Care Technician", "Perfusionist", "Contractor",
    # Radiology & Cardiology
    "Cath Lab Manager", "Cardiac Catheterization Lab Technologist",
    "CT Technologist (Computed Tomography)", "Diagnostic Imaging Assistant",
    "Dosimetrist", "Echocardiography Technologist",
    "EKG Technician (Electrocardiography)", "Electrophysiology Tech",
    "Holter Monitor Stress Test Technician", "Interventional Radiology Tech",
    "Mammography Tech", "Monitor Tech",
    "MRI Technologist (Magnetic Resonance Imaging)", "Nuclear Med Tech",
    "Echocardiography Technologist", "Echocardiography Technologist – Pediatric",
    "Radiation Therapist", "Radiology Manager", "Registered Radiology Assistant",
    "Sonographer", "Special Procedures", "Ultrasound Tech – General",
    "Ultrasound Tech – General II",
    "Ultrasound Tech – Vascular", "Ultrasound Tech – Maternal Fetal", "X-Ray Technologist",
    "Cardiovascular Operating Room Tech",
    # Respiratory & Neuro
    "Certified Hyperbaric Specialist", "Certified Hyperbaric Technician",
    "Certified Respiratory Therapist", "Certified Respiratory Therapist – NICU",
    "EEG Technician (Electroencephalography)", "EEG Technician Manager",
    "Hyperbaric Technician", "Intraoperative Neuromonitoring Tech",
    "Polysomnographer / Sleep Tech", "Pulmonary Function Technologist",
    "Registered Respiratory Therapist", "Registered Respiratory Therapist – Float",
    "Registered Respiratory Therapist – Pediatrics",
    "Registered Respiratory Therapist – PICU",
    "Registered Respiratory Therapist – NICU",
    # Social Services
    "Case Worker", "Certified Social Worker", "Licensed Clinical Social Worker",
    "Licensed Marriage and Family Therapist", "Licensed Professional Clinical Counselor",
    "Licensed Professional Counselor", "Licensed Independent Clinical Social Worker",
    "Licensed Master Social Worker", "Medical Social Worker", "Mental Health",
    "Masters of Social Work", "School Psychologist", "School Social Worker",
    "Social Worker Assistant",
    # Surgical Services
    "Anesthesia Tech", "Certified Anesthesia Tech", "Certified Cardiac First Assist",
    "Certified OB Tech", "Certified Surgical Technologist",
    "Certified Orthopedic Tech", "Certified Surgical First Assistant",
    "Cardiovascular Operating Room Surgical First Assistant",
    "Cardiovascular Operating Room Tech", "Gastrointestinal / Endoscopy Technician",
    "Instrument Tech", "Obstetric Technician",
    "Operating Room Technologist / Surgical Tech",
    "OR Tech First Assistant", "Orthopedic Tech", "Orthotist",
    "Pediatric Cardiovascular Operating Room Tech",
    "Pediatric Operating Room Tech / Surgical Tech",
    "Pediatric Sterile Processing Technician", "Perioperative Assistant",
    "Sterile Processing Technician", "Sterile Processing Director",
    "Sterile Processing Manager", "Sterile Processing Team Lead",
    "Surgical Support Aide",
    # Therapy & Rehab
    "Audiologist",
    "Certified Occupational Therapist Assistant – School",
    "Certified Occupational Therapy Assistant",
    "Certified Occupational Therapy Assistant – Behavioral Health",
    "Certified Occupational Therapy Assistant – Home Health",
    "Certified Occupational Therapy Assistant – Inpatient Rehab",
    "Certified Occupational Therapy Assistant – LTAC",
    "Certified Occupational Therapy Assistant – Outpatient",
    "Certified Occupational Therapy Assistant – Pediatrics",
    "Certified Occupational Therapy Assistant – School",
    "Certified Occupational Therapy Assistant – SNF",
    "Certified Occupational Therapy Assistant – Acute Care",
    "Massage Therapist", "Music Therapist",
    "Occupational Therapist", "Occupational Therapist – School",
    "Occupational Therapist – Acute Care", "Occupational Therapist – Behavioral Health",
    "Occupational Therapist – Home Health", "Occupational Therapist – Inpatient Rehab",
    "Occupational Therapist – LTAC", "Occupational Therapist – Outpatient",
    "Occupational Therapist – Pediatrics", "Occupational Therapist – SNF",
    "Physical Therapist Assistant – School",
    "Physical Therapist", "Physical Therapist – School",
    "Physical Therapist – Acute Care", "Physical Therapist – Behavioral Health",
    "Physical Therapist – Home Health", "Physical Therapist – Inpatient Rehab",
    "Physical Therapist – LTAC", "Physical Therapist – Outpatient",
    "Physical Therapist – Pediatrics", "Physical Therapist – SNF",
    "Physical Therapy Aide",
    "Physical Therapist Assistant", "Physical Therapist Assistant – School",
    "Physical Therapist Assistant – Acute Care",
    "Physical Therapist Assistant – Behavioral Health",
    "Physical Therapist Assistant – Home Health",
    "Physical Therapist Assistant – Inpatient Rehab",
    "Physical Therapist Assistant – LTAC", "Physical Therapist Assistant – Outpatient",
    "Physical Therapist Assistant – Pediatrics", "Physical Therapist Assistant – SNF",
    "Rehab Aide",
    "Speech-Language Pathologist", "Speech-Language Pathologist – Acute Care",
    "Speech-Language Pathologist – Behavioral Health",
    "Speech-Language Pathologist – Home Health",
    "Speech-Language Pathologist – Inpatient Rehab",
    "Speech-Language Pathologist – LTAC", "Speech-Language Pathologist – Outpatient",
    "Speech-Language Pathologist – Pediatrics", "Speech-Language Pathologist – School",
    "Speech-Language Pathologist – SNF",
    "Speech-Language Pathologist Assistant",
    "Speech-Language Pathologist Assistant – Acute Care",
    "Speech-Language Pathologist Assistant – Behavioral Health",
    "Speech-Language Pathologist Assistant – Inpatient Rehab",
    "Speech-Language Pathologist Assistant – LTAC",
    "Speech-Language Pathologist Assistant – Outpatient",
    "Speech-Language Pathologist Assistant – SNF",
    "Speech-Language Pathologist Assistant – School",
]

ALL_SPECIALTIES: list[str] = list(dict.fromkeys(NURSING_SPECIALTIES + ALLIED_HEALTH_SPECIALTIES))


# ── Punctuation-robust matching ───────────────────────────────────────────────
# Resumes and the source spreadsheet disagree on punctuation: en-dash vs hyphen
# ("Ultrasound Tech – General" vs "...- General"), slash spacing ("Med Surg / Tele"
# vs "Med Surg/ Tele"). We match on a normalized key so every variant resolves to
# the same canonical name without enumerating each spelling.


def _match_key(s: str) -> str:
    """Punctuation/whitespace-insensitive lookup key for a specialty string."""
    s = s.replace("–", "-").replace("—", "-")  # en/em dash → hyphen
    s = s.lower().strip()
    s = re.sub(r"\s*/\s*", "/", s)   # collapse spacing around slashes
    s = re.sub(r"\s*-\s*", "-", s)   # collapse spacing around hyphens
    s = re.sub(r"\s+", " ", s)
    return s


_SPECIALTY_BY_KEY:   dict[str, str] = {_match_key(s): s for s in ALL_SPECIALTIES}
_ABBREV_BY_KEY:      dict[str, str] = {_match_key(k): v for k, v in SPECIALTY_ABBREVIATIONS.items()}
_PROF_ABBREV_BY_KEY: dict[str, str] = {_match_key(k): v for k, v in PROFESSION_ABBREVIATIONS.items()}
_PROF_NAME_BY_KEY:   dict[str, str] = {_match_key(v): v for v in PROFESSION_ABBREVIATIONS.values()}
_GROUP_BY_KEY:       dict[str, str] = {_match_key(k): g for k, g in SPECIALTY_GROUPS.items()}


def resolve_specialty(raw: str) -> str | None:
    """
    Resolve a raw skill string to a canonical specialty or profession name.

    Resolution order (all punctuation/case-insensitive):
      1. Canonical specialty name (e.g. "Intensive Care Unit")
      2. Specialty abbreviation/shorthand (e.g. "ICU", "Med Surg/ Tele")
      3. Full profession/credential name (e.g. "Registered Nurse")
      4. Profession/credential abbreviation (e.g. "RN", "OT")
      5. Credential-prefix expansion — "OT - Acute Care" → "Occupational
         Therapist – Acute Care" — so every "<credential> - <setting>" variant
         from the taxonomy resolves without enumerating each setting.

    Returns the canonical name, or None when the string is out-of-taxonomy.
    """
    if not raw or not raw.strip():
        return None

    key = _match_key(raw)
    if key in _SPECIALTY_BY_KEY:
        return _SPECIALTY_BY_KEY[key]
    if key in _ABBREV_BY_KEY:
        return _ABBREV_BY_KEY[key]
    if key in _PROF_NAME_BY_KEY:
        return _PROF_NAME_BY_KEY[key]
    if key in _PROF_ABBREV_BY_KEY:
        return _PROF_ABBREV_BY_KEY[key]

    # Credential-prefix expansion: a single leading token, then a separator.
    m = re.match(r"^\s*([A-Za-z]+)\s*[-–/]\s*(.+)$", raw)
    if m:
        head_key = _match_key(m.group(1))
        expanded = _PROF_ABBREV_BY_KEY.get(head_key) or _ABBREV_BY_KEY.get(head_key)
        if expanded:
            candidate = _match_key(f"{expanded}-{m.group(2)}")
            if candidate in _SPECIALTY_BY_KEY:
                return _SPECIALTY_BY_KEY[candidate]

    return None


def get_specialty_group(specialty: str) -> str | None:
    """Return the group label for a specialty name (punctuation-insensitive)."""
    if specialty in SPECIALTY_GROUPS:
        return SPECIALTY_GROUPS[specialty]
    return _GROUP_BY_KEY.get(_match_key(specialty))


def expand_profession(abbrev: str) -> str:
    """Expand a credential abbreviation to full name, or return as-is."""
    return PROFESSION_ABBREVIATIONS.get(abbrev.lower().strip(), abbrev)


def normalize_specialty(raw: str) -> str:
    """Normalize a specialty string to its canonical name, or return it cleaned."""
    return resolve_specialty(raw) or raw.strip()
